version: "3.9"

services:
  web:
    build: .
    container_name: procash
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  bot:
    build: .
    command: ruby services/telegram_bot.rb
    env_file:
      - .env
    restart: always
