version: "3.9"

services:
  web:
    build: .
    container_name: procash
    ports:
      - "3100:3100"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  bot:
    build: .
    command: ruby bot/telegram_bot.rb
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
